---
services:
  - docker
jobs: 
  include: 
    -
      before_install: 
        - wget https://saw.galois.com/builds/nightly/saw-0.4.0.99-2020-05-21-OSX-64.tar.gz
        - tar -xzf saw-0.4.0.99-2020-05-21-OSX-64.tar.gz
        - export PATH=$PATH:$(pwd)/saw-0.4.0.99-2020-05-21-OSX-64/bin
        - saw --version
        - curl -fsSL https://github.com/Z3Prover/z3/releases/download/z3-4.8.8/z3-4.8.8-x64-osx-10.14.6.zip -o z3-4.8.8-x64-osx-10.14.6.zip
        - unzip -j z3-4.8.8-x64-osx-10.14.6.zip -d z3_downloaded
        - export PATH=$PATH:$(pwd)/z3_downloaded
        - z3 --version
      compiler: clang
      os: osx
    -
      before_install: 
        - brew install cryptol
      compiler: clang
      os: osx
    - 
      before_install: 
        - wget https://saw.galois.com/builds/nightly/saw-0.4.0.99-2020-05-21-Ubuntu14.04-64.tar.gz
        - tar -xzf saw-0.4.0.99-2020-05-21-Ubuntu14.04-64.tar.gz
        - export PATH=$PATH:$(pwd)/saw-0.4.0.99-2020-05-21-Ubuntu14.04-64/bin
        - saw --version
        - curl -fsSL https://github.com/Z3Prover/z3/releases/download/z3-4.8.8/z3-4.8.8-x64-ubuntu-16.04.zip -o z3-4.8.8-x64-ubuntu-16.04.zip
        - unzip -j z3-4.8.8-x64-ubuntu-16.04.zip -d z3_downloaded
        - export PATH=$PATH:$(pwd)/z3_downloaded
        - z3 --version
      compiler: clang
      dist: bionic
      os: linux
language: c
script: 
  - export CRYPTOLPATH=$(pwd)
# Interpreter lab tests
  - cryptol -e -c ":m labs::interpreter::test" -c ":s base=10" -c "x + 2"
  - cryptol -e -b labs/interpreter/test.sry
# Arithmetic verification tests
  - "! command -v saw >/dev/null 2>&1 || make -C labs/saw/arithmetic-verification"
# Bittwiddling lab tests
  - cryptol -e -c ":l labs/saw/bittwiddling/bittwiddling.md"
  - clang -emit-llvm -c labs/saw/bittwiddling/bittwiddling.c -o labs/saw/bittwiddling/bittwiddling.bc
  - cryptol -e -c ":l labs/saw/bittwiddling/bittwiddling_answers.md"
  - "! command -v saw >/dev/null 2>&1 || saw labs/saw/bittwiddling/bittwiddling_answers.saw"
# Salsa20 lab tests
  - cryptol -e -c ":m labs::Salsa20::Salsa20"
  - cryptol -e -c ":m labs::Salsa20::Salsa20Answers"
  - cryptol -e -c ":m labs::Salsa20::Salsa20Props"
  - cryptol -e -c ":m labs::Salsa20::Salsa20PropsAnswers"
# CRC lab tests
  - cryptol -e -c ":m labs::CRC::CRC"
  - cryptol -e -c ":m labs::CRC::CRCAnswers"
# Demo lab tests
  - cryptol -e -c ":m labs::Demos::Caesar"
  - cryptol -e -c ":m labs::Demos::OneTimePad"
  - cryptol -e -c ":m labs::Demos::NQueens"
  - cryptol -e -c ":m labs::Demos::Sudoku"
# Overview lab tests
  - cryptol -e -c ":m labs::Overview::Overview"
# Project Euler lab tests
  - cryptol -e -c ":m labs::ProjectEuler::ProjectEuler"
  - cryptol -e -c ":m labs::ProjectEuler::ProjectEulerAnswers"
# Crypto Proofs lab tests
  - cryptol -e -c ":m labs::CryptoProofs::CryptoProofs"
  - cryptol -e -c ":m labs::CryptoProofs::CryptoProofsAnswers"